# Generated by Django 6.0.3 on 2026-03-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模式名称')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': 'Home Mode',
                'verbose_name_plural': 'Home Modes',
                'db_table': 'brain_home_mode',
            },
        ),
        migrations.CreateModel(
            name='HabitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_did', models.CharField(max_length=128, verbose_name='米家设备 ID')),
                ('property', models.CharField(help_text="例如 'power'", max_length=64, verbose_name='设备属性')),
                ('value', models.CharField(help_text="例如 'off'", max_length=64, verbose_name='预期目标值')),
                ('policy', models.CharField(choices=[('ASK', '主动询问'), ('ALWAYS', '总是直接执行'), ('NEVER', '从不执行(忽略)')], default='ASK', max_length=10, verbose_name='执行策略')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='brain.homemode', verbose_name='所属模式')),
            ],
            options={
                'verbose_name': 'Habit Policy',
                'verbose_name_plural': 'Habit Policies',
                'db_table': 'brain_habit_policy',
                'unique_together': {('mode', 'device_did', 'property')},
            },
        ),
        migrations.CreateModel(
            name='ObservationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.IntegerField(default=0, verbose_name='连续同意(成功)次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后一次同意时间')),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='brain.habitpolicy', verbose_name='绑定规则')),
            ],
            options={
                'verbose_name': 'Observation Counter',
                'verbose_name_plural': 'Observation Counters',
                'db_table': 'brain_observation_counter',
            },
        ),
    ]
