# Generated by Django 6.0.3 on 2026-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Platform Name')),
                ('auth_payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='Auth Payload Data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Platform Auth',
                'verbose_name_plural': 'Platform Auths',
                'db_table': 'platform_auth',
            },
        ),
    ]
