# Generated by Django 6.0.3 on 2026-03-31 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('providers', '0002_update_xiaomi_to_mijia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformauth',
            options={'verbose_name': '三方平台授权', 'verbose_name_plural': '三方平台授权'},
        ),
        migrations.AddField(
            model_name='platformauth',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_auths', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AlterField(
            model_name='platformauth',
            name='auth_payload',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='授权数据载荷'),
        ),
        migrations.AlterField(
            model_name='platformauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='platformauth',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='platformauth',
            name='platform_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='platformauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
