# Generated by Django 6.0.3 on 2026-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='Requester ID')),
                ('original_prompt', models.TextField(verbose_name='Original User Prompt')),
                ('shell_command', models.TextField(verbose_name='Generated Command to Run')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Is Executed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Pending Command',
                'verbose_name_plural': 'Pending Commands',
                'db_table': 'comms_pending_command',
                'ordering': ['-created_at'],
            },
        ),
    ]
