# Generated by Django 6.0.3 on 2026-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcommand',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='服务重启时自动软删除残留的僵尸工单', verbose_name='Is Cancelled'),
        ),
    ]
