# Generated by Django 6.0.3 on 2026-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_pendingcommand_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcommand',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Rich Metadata'),
        ),
    ]
