# Generated by Django 6.0.3 on 2026-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_pendingcommand_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='发起人标识')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('failed', '执行失败'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='任务状态')),
                ('original_prompt', models.TextField(verbose_name='原始输入/触发详情')),
                ('shell_command', models.TextField(blank=True, verbose_name='后端指令/脚本')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='任务元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'comms_mission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PendingCommand',
        ),
    ]
