# Generated by Django 6.0.3 on 2026-03-31 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('comms', '0004_mission_delete_pendingcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.account', verbose_name='所属账户'),
        ),
    ]
