# Generated by Django 6.0.3 on 2026-03-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('comms', '0005_mission_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(db_index=True, max_length=255, verbose_name='发起人标识')),
                ('source', models.CharField(default='wechat', max_length=50, verbose_name='来源平台')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], default='user', max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.account', verbose_name='所属账户')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'comms_chat_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
