# Generated by Django 6.0.3 on 2026-04-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('comms', '0006_chatmessage'),
        ('devices', '0005_expand_device_control_source_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='control_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='目标控制 ID'),
        ),
        migrations.AddField(
            model_name='mission',
            name='control_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='控制项标识'),
        ),
        migrations.AddField(
            model_name='mission',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='目标设备 ID'),
        ),
        migrations.AddField(
            model_name='mission',
            name='operation_action',
            field=models.CharField(blank=True, max_length=32, verbose_name='操作动作'),
        ),
        migrations.AddField(
            model_name='mission',
            name='operation_value',
            field=models.JSONField(blank=True, default=dict, verbose_name='操作目标值'),
        ),
        migrations.AddField(
            model_name='mission',
            name='source_type',
            field=models.CharField(choices=[('shell', 'Shell 指令'), ('device_control', '设备控制'), ('device_clarification', '设备澄清')], default='shell', max_length=32, verbose_name='任务来源类型'),
        ),
        migrations.CreateModel(
            name='DeviceOperationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=255, verbose_name='目标控制 ID')),
                ('control_key', models.CharField(max_length=64, verbose_name='控制项标识')),
                ('operation_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='操作值')),
                ('raw_user_msg', models.TextField(blank=True, verbose_name='原始用户消息')),
                ('normalized_msg', models.TextField(blank=True, verbose_name='归一化消息')),
                ('voice_transcript', models.TextField(blank=True, verbose_name='语音转写文本')),
                ('intent_json', models.JSONField(blank=True, default=dict, verbose_name='意图解析结果')),
                ('resolver_result', models.JSONField(blank=True, default=dict, verbose_name='设备解析结果')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('operated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_operation_contexts', to='accounts.account', verbose_name='所属账户')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_contexts', to='devices.devicesnapshot', verbose_name='目标设备')),
            ],
            options={
                'verbose_name': '设备操作上下文',
                'verbose_name_plural': '设备操作上下文',
                'db_table': 'comms_device_context',
                'ordering': ['-operated_at'],
            },
        ),
    ]
