# Generated by Django 6.0.3 on 2026-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='用户邮箱')),
                ('name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人账户',
                'verbose_name_plural': '个人账户',
                'db_table': 'accounts_account',
                'ordering': ['-created_at'],
            },
        ),
    ]
