# Generated by Django 6.0.3 on 2026-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', help_text='仅存储 PBKDF2 或 Argon2 哈希后的密文', max_length=128, verbose_name='账户密码'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='用户姓名/账号'),
        ),
    ]
