# Generated by Django 6.0.3 on 2026-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_password_alter_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name="用户姓名/账号"),
        ),
    ]
