# Generated by Django 6.0.3 on 2026-03-30 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDashboardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('source', models.CharField(default='demo', max_length=32)),
                ('last_trigger', models.CharField(default='bootstrap', max_length=32)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Dashboard State',
                'verbose_name_plural': 'Device Dashboard States',
                'db_table': 'devices_dashboard_state',
            },
        ),
        migrations.CreateModel(
            name='DeviceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('climate', models.CharField(blank=True, max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Room',
                'verbose_name_plural': 'Device Rooms',
                'db_table': 'devices_room',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('online', 'Online'), ('attention', 'Attention'), ('offline', 'Offline')], default='online', max_length=16)),
                ('telemetry', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.deviceroom')),
            ],
            options={
                'verbose_name': 'Device Snapshot',
                'verbose_name_plural': 'Device Snapshots',
                'db_table': 'devices_snapshot',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('mode_key', models.CharField(max_length=32)),
                ('mode_label', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('ask', 'Ask'), ('always', 'Always'), ('never', 'Never')], default='ask', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='devices.deviceroom')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='devices.devicesnapshot')),
            ],
            options={
                'verbose_name': 'Device Automation Rule',
                'verbose_name_plural': 'Device Automation Rules',
                'db_table': 'devices_automation_rule',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='devices.deviceroom')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='devices.devicesnapshot')),
            ],
            options={
                'verbose_name': 'Device Anomaly',
                'verbose_name_plural': 'Device Anomalies',
                'db_table': 'devices_anomaly',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
    ]
