# Generated by Django 6.0.3 on 2026-03-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedashboardstate',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devicedashboardstate',
            name='refresh_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedashboardstate',
            name='requested_trigger',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='devicedashboardstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
