# Generated by Django 6.0.3 on 2026-03-31 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('devices', '0002_devicedashboardstate_last_error_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceanomaly',
            options={'ordering': ['sort_order', '-updated_at', 'id'], 'verbose_name': '设备异常', 'verbose_name_plural': '设备异常'},
        ),
        migrations.AlterModelOptions(
            name='deviceautomationrule',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '设备自动化规则', 'verbose_name_plural': '设备自动化规则'},
        ),
        migrations.AlterModelOptions(
            name='devicedashboardstate',
            options={'verbose_name': '设备总览状态', 'verbose_name_plural': '设备总览状态'},
        ),
        migrations.AlterModelOptions(
            name='deviceroom',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '设备房间', 'verbose_name_plural': '设备房间'},
        ),
        migrations.AlterModelOptions(
            name='devicesnapshot',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '设备快照', 'verbose_name_plural': '设备快照'},
        ),
        migrations.AddField(
            model_name='deviceanomaly',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_anomalies', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AddField(
            model_name='deviceautomationrule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_automation_rules', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AddField(
            model_name='devicedashboardstate',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_states', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AddField(
            model_name='deviceroom',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AddField(
            model_name='devicesnapshot',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_snapshots', to='accounts.account', verbose_name='所属账户'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='body',
            field=models.TextField(blank=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='检测到的时间'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='devices.devicesnapshot', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='external_id',
            field=models.CharField(max_length=128, verbose_name='外部异常 ID'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否处于激活态'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='处理建议'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='devices.deviceroom', verbose_name='关联房间'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='severity',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='low', max_length=16, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='title',
            field=models.CharField(max_length=255, verbose_name='异常标题'),
        ),
        migrations.AlterField(
            model_name='deviceanomaly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='condition',
            field=models.TextField(blank=True, verbose_name='生效条件描述'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='decision',
            field=models.CharField(choices=[('ask', '需确认'), ('always', '自动执行'), ('never', '从不执行')], default='ask', max_length=16, verbose_name='执行决策方式'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='devices.devicesnapshot', verbose_name='关联设备'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='external_id',
            field=models.CharField(max_length=128, verbose_name='外部规则 ID'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='mode_key',
            field=models.CharField(help_text="如 'away'", max_length=32, verbose_name='模式标识'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='mode_label',
            field=models.CharField(help_text="如 '离家'", max_length=64, verbose_name='模式显示名称'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='rationale',
            field=models.TextField(blank=True, verbose_name='决策依据建议'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='devices.deviceroom', verbose_name='关联房间'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='target',
            field=models.CharField(help_text="如 '客厅灯 / 开关'", max_length=255, verbose_name='策略目标字段'),
        ),
        migrations.AlterField(
            model_name='deviceautomationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='key',
            field=models.CharField(default='default', max_length=32, verbose_name='状态标识'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='上次错误信息'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='last_trigger',
            field=models.CharField(default='bootstrap', max_length=32, verbose_name='上次触发行为'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='refresh_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='请求刷新时间'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近成功刷新时间'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='requested_trigger',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='正在请求的触发行为'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='source',
            field=models.CharField(default='demo', max_length=32, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='devicedashboardstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='climate',
            field=models.CharField(blank=True, help_text="如 '26°C / 58% RH'", max_length=128, verbose_name='环境概览文字'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='name',
            field=models.CharField(max_length=64, verbose_name='房间名称'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='房间标识'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='summary',
            field=models.TextField(blank=True, verbose_name='房间摘要描述'),
        ),
        migrations.AlterField(
            model_name='deviceroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, verbose_name='可用能力列表'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='category',
            field=models.CharField(max_length=64, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='external_id',
            field=models.CharField(max_length=128, verbose_name='外部设备 ID'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近活动时间'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='name',
            field=models.CharField(max_length=128, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='note',
            field=models.TextField(blank=True, verbose_name='系统备注'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.deviceroom', verbose_name='关联房间'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序权重'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始数据报文'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('attention', '需留意'), ('offline', '离线')], default='online', max_length=16, verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='telemetry',
            field=models.CharField(blank=True, help_text="如 '已开启 / 68% 亮度'", max_length=255, verbose_name='遥测摘要'),
        ),
        migrations.AlterField(
            model_name='devicesnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceanomaly',
            unique_together={('account', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceautomationrule',
            unique_together={('account', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='devicedashboardstate',
            unique_together={('account', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceroom',
            unique_together={('account', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='devicesnapshot',
            unique_together={('account', 'external_id')},
        ),
    ]
