# Generated by Django 6.0.3 on 2026-04-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
        ('devices', '0003_alter_deviceanomaly_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='外部控制 ID')),
                ('parent_external_id', models.CharField(blank=True, max_length=255, verbose_name='父级控制 ID')),
                ('source_type', models.CharField(choices=[('ha_entity', 'Home Assistant 实体'), ('mijia_property', '米家属性'), ('mijia_action', '米家动作')], max_length=32, verbose_name='来源类型')),
                ('kind', models.CharField(choices=[('sensor', '传感器'), ('toggle', '开关'), ('range', '范围控制'), ('enum', '枚举控制'), ('action', '动作'), ('text', '文本')], default='sensor', max_length=16, verbose_name='控制类型')),
                ('key', models.CharField(max_length=128, verbose_name='控制标识')),
                ('label', models.CharField(max_length=128, verbose_name='控制名称')),
                ('group_label', models.CharField(blank=True, max_length=128, verbose_name='分组名称')),
                ('writable', models.BooleanField(default=False, verbose_name='是否可写')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='当前值')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='可选项')),
                ('range_spec', models.JSONField(blank=True, default=dict, verbose_name='范围规格')),
                ('action_params', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='原始数据报文')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序权重')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_controls', to='accounts.account', verbose_name='所属账户')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='devices.devicesnapshot', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备控制节点',
                'verbose_name_plural': '设备控制节点',
                'db_table': 'devices_control',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('account', 'external_id')},
            },
        ),
    ]
