# Generated by Django 6.0.3 on 2026-04-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0003_add_aggregated_from"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caresuggestion",
            options={
                "ordering": ["-priority", "-created_at", "-id"],
                "verbose_name": "关怀建议",
                "verbose_name_plural": "关怀建议",
            },
        ),
        migrations.AlterModelOptions(
            name="externaldatasource",
            options={
                "ordering": ["account_id", "name", "id"],
                "verbose_name": "外部数据源",
                "verbose_name_plural": "外部数据源",
            },
        ),
        migrations.AlterModelOptions(
            name="inspectionrule",
            options={
                "ordering": ["account_id", "-is_system_default", "name", "id"],
                "verbose_name": "巡检规则",
                "verbose_name_plural": "巡检规则",
            },
        ),
    ]
