# Generated by Django 6.0.3 on 2026-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='User ID')),
                ('message', models.TextField(verbose_name='Push Message')),
                ('feedback', models.CharField(choices=[('APPROVED', '已采纳'), ('DENIED', '已拒绝'), ('IGNORED', '已忽略'), ('PENDING', '等待反馈')], default='PENDING', max_length=20, verbose_name='User Feedback')),
                ('score', models.FloatField(default=0.0, help_text='推送时的评分：环境紧急度 × 画像匹配度 × 反馈权重', verbose_name='Impact Score')),
                ('source', models.CharField(default='daily_review', help_text='触发来源：daily_review, monitor, manual', max_length=100, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proactive Log',
                'verbose_name_plural': 'Proactive Logs',
                'db_table': 'memory_proactive_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='User ID')),
                ('category', models.CharField(choices=[('Environment', '环境偏好'), ('Entertainment', '娱乐偏好'), ('Habit', '日常习惯'), ('Device', '设备偏好'), ('Other', '其他')], default='Other', max_length=50, verbose_name='Category')),
                ('key', models.CharField(help_text='偏好键，如 preferred_temp, bedtime_routine', max_length=255, verbose_name='Preference Key')),
                ('value', models.TextField(help_text='偏好值，如 24, 23:00', verbose_name='Preference Value')),
                ('confidence', models.FloatField(default=0.5, help_text='置信度 0.0 - 1.0', verbose_name='Confidence')),
                ('last_confirmed', models.DateTimeField(blank=True, help_text='上次用户确认的时间', null=True, verbose_name='Last Confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'memory_user_profile',
                'ordering': ['-confidence', '-updated_at'],
                'unique_together': {('user_id', 'key')},
            },
        ),
    ]
