# Generated by Django 6.0.3 on 2026-03-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_password_alter_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='推送消息')),
                ('feedback', models.CharField(choices=[('APPROVED', '已采纳'), ('DENIED', '已拒绝'), ('IGNORED', '已忽略'), ('PENDING', '等待反馈')], default='PENDING', max_length=20, verbose_name='用户反馈')),
                ('score', models.FloatField(default=0.0, help_text='推送时的评分：环境紧急度 × 画像匹配度 × 反馈权重', verbose_name='影响分')),
                ('source', models.CharField(default='daily_review', help_text='触发来源：daily_review, monitor, manual', max_length=100, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '主动关怀日志',
                'verbose_name_plural': '主动关怀日志',
                'db_table': 'memory_proactive_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Environment', '环境偏好'), ('Entertainment', '娱乐偏好'), ('Habit', '日常习惯'), ('Device', '设备偏好'), ('Other', '其他')], default='Other', max_length=50, verbose_name='类别')),
                ('key', models.CharField(help_text='偏好键，如 preferred_temp, bedtime_routine', max_length=255, verbose_name='偏好键')),
                ('value', models.TextField(help_text='偏好值，如 24, 23:00', verbose_name='偏好值')),
                ('confidence', models.FloatField(default=0.5, help_text='置信度 0.0 - 1.0', verbose_name='置信度')),
                ('source', models.CharField(choices=[('review', '定时复盘'), ('manual', '用户手动修改')], default='review', help_text='当前画像值的来源：定时复盘或用户手动修改', max_length=20, verbose_name='来源')),
                ('is_user_edited', models.BooleanField(default=False, help_text='是否由用户手动修改；若为 True，后续复盘应优先保留该值', verbose_name='是否为用户编辑')),
                ('last_confirmed', models.DateTimeField(blank=True, help_text='上次用户确认的时间', null=True, verbose_name='上次确认时间')),
                ('last_review_value', models.TextField(blank=True, default='', help_text='当用户手动修改后，最近一次定时复盘建议的值会记录在这里，供后续融合或审计', verbose_name='上次复盘建议值')),
                ('last_review_confidence', models.FloatField(blank=True, help_text='最近一次复盘建议的置信度', null=True, verbose_name='上次复盘置信度')),
                ('last_review_at', models.DateTimeField(blank=True, help_text='最近一次复盘处理该画像的时间', null=True, verbose_name='上次复盘时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='关联账户')),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
                'db_table': 'memory_user_profile',
                'ordering': ['-confidence', '-updated_at'],
                'unique_together': {('account', 'key')},
            },
        ),
    ]
